[platformio]
default_envs = viewe_s3_diag
core_dir = D:\platformio_diag

[env:viewe_s3_diag]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
board = BOARD_VIEWE_UEDX24320028E_WB_A_DIAG
monitor_speed = 115200
upload_speed = 921600
upload_port = COM8
monitor_port = COM8
build_type = debug
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
